#
# ----------------------------------------
# RS Plugin Template Configuration
# ----------------------------------------

# Maximum lightning rod segments allowed for an Auger.
# Values above 16 are ignored.
# Allowed Range: 1-16
# Default: 16
max-machine-length: 16

